# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_service.proto',
  package='endpoints.flunky.simulator',
  syntax='proto3',
  serialized_options=b'\n*de.flunkyteam.endpoints.projects.simulatorB\006ClientP\001',
  serialized_pb=b'\n\x14\x63lient_service.proto\x12\x1a\x65ndpoints.flunky.simulator\"\x11\n\x0f\x43lientStreamReq\"\xaf\x01\n\x10\x43lientStreamResp\x12\x46\n\x0f\x63lientRegisterd\x18\x01 \x01(\x0b\x32+.endpoints.flunky.simulator.ClientRegisterdH\x00\x12\x44\n\x0e\x61liveChallenge\x18\x02 \x01(\x0b\x32*.endpoints.flunky.simulator.AliveChallengeH\x00\x42\r\n\x0b\x65vent_oneof\"!\n\x0f\x43lientRegisterd\x12\x0e\n\x06secret\x18\x01 \x01(\t\"\x10\n\x0e\x41liveChallenge2|\n\rClientService\x12k\n\x0c\x43lientStream\x12+.endpoints.flunky.simulator.ClientStreamReq\x1a,.endpoints.flunky.simulator.ClientStreamResp0\x01\x42\x36\n*de.flunkyteam.endpoints.projects.simulatorB\x06\x43lientP\x01\x62\x06proto3'
)




_CLIENTSTREAMREQ = _descriptor.Descriptor(
  name='ClientStreamReq',
  full_name='endpoints.flunky.simulator.ClientStreamReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=69,
)


_CLIENTSTREAMRESP = _descriptor.Descriptor(
  name='ClientStreamResp',
  full_name='endpoints.flunky.simulator.ClientStreamResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientRegisterd', full_name='endpoints.flunky.simulator.ClientStreamResp.clientRegisterd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aliveChallenge', full_name='endpoints.flunky.simulator.ClientStreamResp.aliveChallenge', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event_oneof', full_name='endpoints.flunky.simulator.ClientStreamResp.event_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=72,
  serialized_end=247,
)


_CLIENTREGISTERD = _descriptor.Descriptor(
  name='ClientRegisterd',
  full_name='endpoints.flunky.simulator.ClientRegisterd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secret', full_name='endpoints.flunky.simulator.ClientRegisterd.secret', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=282,
)


_ALIVECHALLENGE = _descriptor.Descriptor(
  name='AliveChallenge',
  full_name='endpoints.flunky.simulator.AliveChallenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=300,
)

_CLIENTSTREAMRESP.fields_by_name['clientRegisterd'].message_type = _CLIENTREGISTERD
_CLIENTSTREAMRESP.fields_by_name['aliveChallenge'].message_type = _ALIVECHALLENGE
_CLIENTSTREAMRESP.oneofs_by_name['event_oneof'].fields.append(
  _CLIENTSTREAMRESP.fields_by_name['clientRegisterd'])
_CLIENTSTREAMRESP.fields_by_name['clientRegisterd'].containing_oneof = _CLIENTSTREAMRESP.oneofs_by_name['event_oneof']
_CLIENTSTREAMRESP.oneofs_by_name['event_oneof'].fields.append(
  _CLIENTSTREAMRESP.fields_by_name['aliveChallenge'])
_CLIENTSTREAMRESP.fields_by_name['aliveChallenge'].containing_oneof = _CLIENTSTREAMRESP.oneofs_by_name['event_oneof']
DESCRIPTOR.message_types_by_name['ClientStreamReq'] = _CLIENTSTREAMREQ
DESCRIPTOR.message_types_by_name['ClientStreamResp'] = _CLIENTSTREAMRESP
DESCRIPTOR.message_types_by_name['ClientRegisterd'] = _CLIENTREGISTERD
DESCRIPTOR.message_types_by_name['AliveChallenge'] = _ALIVECHALLENGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientStreamReq = _reflection.GeneratedProtocolMessageType('ClientStreamReq', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSTREAMREQ,
  '__module__' : 'client_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.ClientStreamReq)
  })
_sym_db.RegisterMessage(ClientStreamReq)

ClientStreamResp = _reflection.GeneratedProtocolMessageType('ClientStreamResp', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSTREAMRESP,
  '__module__' : 'client_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.ClientStreamResp)
  })
_sym_db.RegisterMessage(ClientStreamResp)

ClientRegisterd = _reflection.GeneratedProtocolMessageType('ClientRegisterd', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREGISTERD,
  '__module__' : 'client_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.ClientRegisterd)
  })
_sym_db.RegisterMessage(ClientRegisterd)

AliveChallenge = _reflection.GeneratedProtocolMessageType('AliveChallenge', (_message.Message,), {
  'DESCRIPTOR' : _ALIVECHALLENGE,
  '__module__' : 'client_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.AliveChallenge)
  })
_sym_db.RegisterMessage(AliveChallenge)


DESCRIPTOR._options = None

_CLIENTSERVICE = _descriptor.ServiceDescriptor(
  name='ClientService',
  full_name='endpoints.flunky.simulator.ClientService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=302,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClientStream',
    full_name='endpoints.flunky.simulator.ClientService.ClientStream',
    index=0,
    containing_service=None,
    input_type=_CLIENTSTREAMREQ,
    output_type=_CLIENTSTREAMRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENTSERVICE)

DESCRIPTOR.services_by_name['ClientService'] = _CLIENTSERVICE

# @@protoc_insertion_point(module_scope)
