# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import client_service_pb2 as client__service__pb2


class ClientServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ClientStream = channel.unary_stream(
        '/endpoints.flunky.simulator.ClientService/ClientStream',
        request_serializer=client__service__pb2.ClientStreamReq.SerializeToString,
        response_deserializer=client__service__pb2.ClientStreamResp.FromString,
        )


class ClientServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ClientStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ClientStream': grpc.unary_stream_rpc_method_handler(
          servicer.ClientStream,
          request_deserializer=client__service__pb2.ClientStreamReq.FromString,
          response_serializer=client__service__pb2.ClientStreamResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'endpoints.flunky.simulator.ClientService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
