# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_service.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video_service.proto',
  package='endpoints.flunky.simulator',
  syntax='proto3',
  serialized_options=b'\n*de.flunkyteam.endpoints.projects.simulatorB\005VideoP\001',
  serialized_pb=b'\n\x13video_service.proto\x12\x1a\x65ndpoints.flunky.simulator\"N\n\x15StreamVideoEventsResp\x12\x35\n\x05\x65vent\x18\x01 \x01(\x0b\x32&.endpoints.flunky.simulator.VideoEvent\"\x16\n\x14StreamVideoEventsReq\"\xa5\x01\n\nVideoEvent\x12\x45\n\x0cprepareVideo\x18\x01 \x01(\x0b\x32-.endpoints.flunky.simulator.PrepareVideoEventH\x00\x12\x41\n\nplayVideos\x18\x02 \x01(\x0b\x32+.endpoints.flunky.simulator.PlayVideosEventH\x00\x42\r\n\x0b\x65vent_oneof\"^\n\x11PrepareVideoEvent\x12\x0b\n\x03url\x18\x01 \x01(\t\x12<\n\tvideoType\x18\x02 \x01(\x0e\x32).endpoints.flunky.simulator.EnumVideoType\"I\n\x0fPlayVideosEvent\x12\x36\n\x06videos\x18\x01 \x03(\x0b\x32&.endpoints.flunky.simulator.TimedVideo\"k\n\nTimedVideo\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x03\x12<\n\tvideoType\x18\x02 \x01(\x0e\x32).endpoints.flunky.simulator.EnumVideoType\x12\x10\n\x08mirrored\x18\x03 \x01(\x08*\xa8\x01\n\rEnumVideoType\x12\x15\n\x11UNKNOWN_VIDEOTYPE\x10\x00\x12\x13\n\x0fSETUP_VIDEOTYPE\x10\x01\x12\x11\n\rHIT_VIDEOTYPE\x10\x02\x12\x12\n\x0eMISS_VIDEOTYPE\x10\x03\x12\x17\n\x13NEAR_MISS_VIDEOTYPE\x10\x04\x12\x12\n\x0eSTOP_VIDEOTYPE\x10\x05\x12\x17\n\x13STRAFBIER_VIDEOTYPE\x10\x06\x32\x8a\x01\n\x0cVideoService\x12z\n\x11StreamVideoEvents\x12\x30.endpoints.flunky.simulator.StreamVideoEventsReq\x1a\x31.endpoints.flunky.simulator.StreamVideoEventsResp0\x01\x42\x35\n*de.flunkyteam.endpoints.projects.simulatorB\x05VideoP\x01\x62\x06proto3'
)

_ENUMVIDEOTYPE = _descriptor.EnumDescriptor(
  name='EnumVideoType',
  full_name='endpoints.flunky.simulator.EnumVideoType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_VIDEOTYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SETUP_VIDEOTYPE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIT_VIDEOTYPE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISS_VIDEOTYPE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEAR_MISS_VIDEOTYPE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_VIDEOTYPE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRAFBIER_VIDEOTYPE', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=604,
  serialized_end=772,
)
_sym_db.RegisterEnumDescriptor(_ENUMVIDEOTYPE)

EnumVideoType = enum_type_wrapper.EnumTypeWrapper(_ENUMVIDEOTYPE)
UNKNOWN_VIDEOTYPE = 0
SETUP_VIDEOTYPE = 1
HIT_VIDEOTYPE = 2
MISS_VIDEOTYPE = 3
NEAR_MISS_VIDEOTYPE = 4
STOP_VIDEOTYPE = 5
STRAFBIER_VIDEOTYPE = 6



_STREAMVIDEOEVENTSRESP = _descriptor.Descriptor(
  name='StreamVideoEventsResp',
  full_name='endpoints.flunky.simulator.StreamVideoEventsResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='endpoints.flunky.simulator.StreamVideoEventsResp.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=129,
)


_STREAMVIDEOEVENTSREQ = _descriptor.Descriptor(
  name='StreamVideoEventsReq',
  full_name='endpoints.flunky.simulator.StreamVideoEventsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=153,
)


_VIDEOEVENT = _descriptor.Descriptor(
  name='VideoEvent',
  full_name='endpoints.flunky.simulator.VideoEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prepareVideo', full_name='endpoints.flunky.simulator.VideoEvent.prepareVideo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playVideos', full_name='endpoints.flunky.simulator.VideoEvent.playVideos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event_oneof', full_name='endpoints.flunky.simulator.VideoEvent.event_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=156,
  serialized_end=321,
)


_PREPAREVIDEOEVENT = _descriptor.Descriptor(
  name='PrepareVideoEvent',
  full_name='endpoints.flunky.simulator.PrepareVideoEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='endpoints.flunky.simulator.PrepareVideoEvent.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='videoType', full_name='endpoints.flunky.simulator.PrepareVideoEvent.videoType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=417,
)


_PLAYVIDEOSEVENT = _descriptor.Descriptor(
  name='PlayVideosEvent',
  full_name='endpoints.flunky.simulator.PlayVideosEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videos', full_name='endpoints.flunky.simulator.PlayVideosEvent.videos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=492,
)


_TIMEDVIDEO = _descriptor.Descriptor(
  name='TimedVideo',
  full_name='endpoints.flunky.simulator.TimedVideo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay', full_name='endpoints.flunky.simulator.TimedVideo.delay', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='videoType', full_name='endpoints.flunky.simulator.TimedVideo.videoType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mirrored', full_name='endpoints.flunky.simulator.TimedVideo.mirrored', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=601,
)

_STREAMVIDEOEVENTSRESP.fields_by_name['event'].message_type = _VIDEOEVENT
_VIDEOEVENT.fields_by_name['prepareVideo'].message_type = _PREPAREVIDEOEVENT
_VIDEOEVENT.fields_by_name['playVideos'].message_type = _PLAYVIDEOSEVENT
_VIDEOEVENT.oneofs_by_name['event_oneof'].fields.append(
  _VIDEOEVENT.fields_by_name['prepareVideo'])
_VIDEOEVENT.fields_by_name['prepareVideo'].containing_oneof = _VIDEOEVENT.oneofs_by_name['event_oneof']
_VIDEOEVENT.oneofs_by_name['event_oneof'].fields.append(
  _VIDEOEVENT.fields_by_name['playVideos'])
_VIDEOEVENT.fields_by_name['playVideos'].containing_oneof = _VIDEOEVENT.oneofs_by_name['event_oneof']
_PREPAREVIDEOEVENT.fields_by_name['videoType'].enum_type = _ENUMVIDEOTYPE
_PLAYVIDEOSEVENT.fields_by_name['videos'].message_type = _TIMEDVIDEO
_TIMEDVIDEO.fields_by_name['videoType'].enum_type = _ENUMVIDEOTYPE
DESCRIPTOR.message_types_by_name['StreamVideoEventsResp'] = _STREAMVIDEOEVENTSRESP
DESCRIPTOR.message_types_by_name['StreamVideoEventsReq'] = _STREAMVIDEOEVENTSREQ
DESCRIPTOR.message_types_by_name['VideoEvent'] = _VIDEOEVENT
DESCRIPTOR.message_types_by_name['PrepareVideoEvent'] = _PREPAREVIDEOEVENT
DESCRIPTOR.message_types_by_name['PlayVideosEvent'] = _PLAYVIDEOSEVENT
DESCRIPTOR.message_types_by_name['TimedVideo'] = _TIMEDVIDEO
DESCRIPTOR.enum_types_by_name['EnumVideoType'] = _ENUMVIDEOTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamVideoEventsResp = _reflection.GeneratedProtocolMessageType('StreamVideoEventsResp', (_message.Message,), {
  'DESCRIPTOR' : _STREAMVIDEOEVENTSRESP,
  '__module__' : 'video_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.StreamVideoEventsResp)
  })
_sym_db.RegisterMessage(StreamVideoEventsResp)

StreamVideoEventsReq = _reflection.GeneratedProtocolMessageType('StreamVideoEventsReq', (_message.Message,), {
  'DESCRIPTOR' : _STREAMVIDEOEVENTSREQ,
  '__module__' : 'video_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.StreamVideoEventsReq)
  })
_sym_db.RegisterMessage(StreamVideoEventsReq)

VideoEvent = _reflection.GeneratedProtocolMessageType('VideoEvent', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOEVENT,
  '__module__' : 'video_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.VideoEvent)
  })
_sym_db.RegisterMessage(VideoEvent)

PrepareVideoEvent = _reflection.GeneratedProtocolMessageType('PrepareVideoEvent', (_message.Message,), {
  'DESCRIPTOR' : _PREPAREVIDEOEVENT,
  '__module__' : 'video_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.PrepareVideoEvent)
  })
_sym_db.RegisterMessage(PrepareVideoEvent)

PlayVideosEvent = _reflection.GeneratedProtocolMessageType('PlayVideosEvent', (_message.Message,), {
  'DESCRIPTOR' : _PLAYVIDEOSEVENT,
  '__module__' : 'video_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.PlayVideosEvent)
  })
_sym_db.RegisterMessage(PlayVideosEvent)

TimedVideo = _reflection.GeneratedProtocolMessageType('TimedVideo', (_message.Message,), {
  'DESCRIPTOR' : _TIMEDVIDEO,
  '__module__' : 'video_service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.flunky.simulator.TimedVideo)
  })
_sym_db.RegisterMessage(TimedVideo)


DESCRIPTOR._options = None

_VIDEOSERVICE = _descriptor.ServiceDescriptor(
  name='VideoService',
  full_name='endpoints.flunky.simulator.VideoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=775,
  serialized_end=913,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamVideoEvents',
    full_name='endpoints.flunky.simulator.VideoService.StreamVideoEvents',
    index=0,
    containing_service=None,
    input_type=_STREAMVIDEOEVENTSREQ,
    output_type=_STREAMVIDEOEVENTSRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIDEOSERVICE)

DESCRIPTOR.services_by_name['VideoService'] = _VIDEOSERVICE

# @@protoc_insertion_point(module_scope)
