version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "11049:11049"
  backendproxy:
    container_name: backendproxy
    command: [ "--backend_addr=backend:11049" ]
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: docker/backendproxy/Dockerfile
  frontend:
    container_name: frontend
    environment:
      - BACKEND_URL=http://localhost:8080
    #     - BACKEND_URL=<server url>:8443
    ports:
      - 80:5000
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile