name: Publish Docker

on:
  push:    
    branches: [ 'master', 'develop' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build_d_f
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upbflunkyteamdev/flunkysimulator-frontend:dev
          file: docker/frontend/Dockerfile
      - name: Build and push
        id: docker_build_d_bp
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upbflunkyteamdev/flunkysimulator-backendproxy:dev
          file: docker/backendproxy/Dockerfile
      - name: Build and push
        id: docker_build_d_b
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upbflunkyteamdev/flunkysimulator-backend:dev
          file: docker/backend/Dockerfile
          
      - name: Build and push
        id: docker_build_m_f
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upbflunkyteamdev/flunkysimulator-frontend:latest
          file: docker/frontend/Dockerfile
      - name: Build and push
        id: docker_build_m_bp
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upbflunkyteamdev/flunkysimulator-backendproxy:latest
          file: docker/backendproxy/Dockerfile
      - name: Build and push
        id: docker_build_m_b
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upbflunkyteamdev/flunkysimulator-backend:latest
          file: docker/backend/Dockerfile
        
